# Generated by Django 4.1.5 on 2023-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                (
                    "admin",
                    models.CharField(
                        choices=[
                            ("R", "Regular - Can't delete members"),
                            ("A", "Admin - Can delete members"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
